### ISSUE TITLE
bypass localization

### ISSUE THREAD

**Issue by wvengen** [bennibu/localize_input#1]
When creating a record that uses localize_input in code, it may not be desired to have a localized version, e.g. when interacting with outside systems. There should be a way to set variables unlocalized too.

I have this with foodsoft's FinancialTransaction.amount. I'd like to create a new transaction with the amount coming from the code - not entered by the user. This is current impossible without either disabling localize_input or first doing the reverse action.

**Comment by bennibu** [comment]
hmm, this shouldn't be a problem, because, the '.' will only be removed, when the number matches '1.000,00'. So a string like '1234.45' would not be modified.

When you pass an BigDecimal, Float or Int, the number shouldn't be modified too.

**Comment by wvengen** [comment]
True! I can't reproduce the problem anymore ...
